# Generated by Django 2.0 on 2017-12-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='idd',
            new_name='Category',
        ),
    ]
