# Generated by Django 2.0 on 2017-12-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='SubCategory',
        ),
    ]
